// Code generated by "stringer -type=currencyType"; DO NOT EDIT

package scan

import "fmt"

const _currencyType_name = "nilTypeusdeurplngbpchf"

var _currencyType_index = [...]uint8{0, 7, 10, 13, 16, 19, 22}

func (i currencyType) String() string {
	if i < 0 || i >= currencyType(len(_currencyType_index)-1) {
		return fmt.Sprintf("currencyType(%d)", i)
	}
	return _currencyType_name[_currencyType_index[i]:_currencyType_index[i+1]]
}
