// Code generated by "stringer -type=itemType"; DO NOT EDIT

package scan

import "fmt"

const _itemType_name = "itemEofitemNumberitemIdentifieritemEqualitemAdditemSubitemMulitemDivitemLParenitemRParenitemError"

var _itemType_index = [...]uint8{0, 7, 17, 31, 40, 47, 54, 61, 68, 78, 88, 97}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
