// Code generated by "stringer -type=typeGroup"; DO NOT EDIT

package datatype

import "fmt"

const _typeGroup_name = "GroupBareGroupLengthGroupWeightGroupTemperatureGroupVolumeGroupTimeGroupCurrencyGroupDataSize"

var _typeGroup_index = [...]uint8{0, 9, 20, 31, 47, 58, 67, 80, 93}

func (i typeGroup) String() string {
	if i < 0 || i >= typeGroup(len(_typeGroup_index)-1) {
		return fmt.Sprintf("typeGroup(%d)", i)
	}
	return _typeGroup_name[_typeGroup_index[i]:_typeGroup_index[i+1]]
}
